const express=require('express');
const crypto=require('node:crypto');
const Stripe=require('stripe');
const {securityMiddleware}=require('./src/security');
const {query,getClient,isDatabaseConfigured,closeDatabase}=require('./src/db');
const {initializeDatabase}=require('./src/init-db');
const {hashPassword,verifyPassword,signToken,requireAuth,requireAdmin}=require('./src/auth');

const app=express();
const PORT=Number(process.env.PORT)||3000;
const stripe=process.env.STRIPE_SECRET_KEY?new Stripe(process.env.STRIPE_SECRET_KEY):null;
securityMiddleware(app);
const allowedOrigins=(process.env.FRONTEND_ORIGIN||process.env.CLIENT_ORIGIN||'').split(',').map(v=>v.trim()).filter(Boolean);
app.use((req,res,next)=>{const origin=req.get('origin');if(origin&&allowedOrigins.includes(origin)){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');}if(req.method==='OPTIONS')return res.sendStatus(204);next()});
app.use('/api/payments/webhook',express.raw({type:'application/json'}));
app.use(express.json({limit:'1mb'}));
const id=p=>`${p}-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(4).toString('hex').toUpperCase()}`;
const trackingId=()=>`TMX-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${crypto.randomBytes(4).toString('hex').toUpperCase()}`;
const vehicleFromRow=r=>({id:r.id,model:r.model,year:r.year,price:Number(r.price),range:r.range_miles,status:r.status,imageUrl:r.image_url||undefined,metadata:r.metadata||{}});
const orderFromRow=r=>({id:r.id,trackingId:r.tracking_id,vehicleId:r.vehicle_id,configurationId:r.configuration_id,customer:{name:r.customer_name,email:r.customer_email,phone:r.customer_phone||''},total:Number(r.total),depositAmount:Number(r.deposit_amount),status:r.status,notes:r.notes||'',createdAt:r.created_at});
async function databaseReady(){if(!isDatabaseConfigured())return false;await query('SELECT 1');return true}
app.get('/health',async(_q,res)=>{let connected=false;try{connected=await databaseReady()}catch{}res.status(200).json({status:'ok',service:'TeslaMarketplace API',database:connected?'connected':'disconnected',stripe:stripe?'configured':'not_configured',timestamp:new Date().toISOString()})});
app.get('/api/health',async(_q,res)=>{let connected=false;try{connected=await databaseReady()}catch{}res.json({status:'ok',database:connected?'connected':'disconnected',stripe:stripe?'configured':'not_configured'})});
app.get('/api',(_q,res)=>res.json({name:'TeslaMarketplace API',version:'4.0.0',persistence:'postgresql',payments:'stripe'}));

app.post('/api/auth/register',async(req,res,next)=>{try{const{name,email,password,phone=''}=req.body||{};if(!name||!email||!password)return res.status(400).json({error:'Name, email and password are required'});if(String(password).length<8)return res.status(400).json({error:'Password must be at least 8 characters'});const normalizedEmail=String(email).trim().toLowerCase();const passwordHash=await hashPassword(String(password));const result=await query(`INSERT INTO users (id,name,email,phone,password_hash) VALUES ($1,$2,$3,$4,$5) RETURNING id,name,email,phone,role,created_at`,[id('USR'),String(name).trim(),normalizedEmail,phone,passwordHash]);const user=result.rows[0];res.status(201).json({data:{user,token:signToken({userId:user.id,role:user.role})}})}catch(e){if(e.code==='23505')return res.status(409).json({error:'An account with that email already exists'});next(e)}});
app.post('/api/auth/login',async(req,res,next)=>{try{const{email,password}=req.body||{};if(!email||!password)return res.status(400).json({error:'Email and password are required'});const{rows}=await query(`SELECT id,name,email,phone,role,password_hash FROM users WHERE email=$1`,[String(email).trim().toLowerCase()]);if(!rows[0]||!rows[0].password_hash||!(await verifyPassword(String(password),rows[0].password_hash)))return res.status(401).json({error:'Invalid email or password'});const user=rows[0];delete user.password_hash;res.json({data:{user,token:signToken({userId:user.id,role:user.role})}})}catch(e){next(e)}});
app.get('/api/me',requireAuth,async(req,res,next)=>{try{const{rows}=await query(`SELECT id,name,email,phone,role,created_at FROM users WHERE id=$1`,[req.user.userId]);if(!rows[0])return res.status(404).json({error:'User not found'});res.json({data:rows[0]})}catch(e){next(e)}});

app.get('/api/vehicles',async(req,res,next)=>{try{const params=[];let sql=`SELECT id,model,year,price,range_miles,status,image_url,metadata FROM vehicles WHERE status<>'draft'`;const{q,model,minPrice,maxPrice,zip}=req.query;if(q){params.push(`%${String(q).trim().toLowerCase()}%`);sql+=` AND LOWER(model||' '||COALESCE(metadata->>'trim','')||' '||COALESCE(metadata->>'color','')) LIKE $${params.length}`}if(model&&model!=='all'){params.push(model);sql+=` AND model=$${params.length}`}if(minPrice){params.push(Number(minPrice));sql+=` AND price >= $${params.length}`}if(maxPrice){params.push(Number(maxPrice));sql+=` AND price <= $${params.length}`}if(zip){params.push(String(zip).trim());sql+=` AND COALESCE(metadata->>'zip','')=$${params.length}`}sql+=' ORDER BY created_at,id';const{rows}=await query(sql,params);res.json({data:rows.map(vehicleFromRow)})}catch(e){next(e)}});
app.get('/api/vehicles/:id',async(req,res,next)=>{try{const{rows}=await query(`SELECT id,model,year,price,range_miles,status,image_url,metadata FROM vehicles WHERE id=$1`,[req.params.id]);if(!rows[0])return res.status(404).json({error:'Vehicle not found'});res.json({data:vehicleFromRow(rows[0])})}catch(e){next(e)}});
app.get('/api/configurator/options',async(req,res,next)=>{try{const model=String(req.query.model||'Model Y');const{rows}=await query(`SELECT id,vehicle_model,category,option_name,additional_price,image_url,metadata FROM vehicle_options WHERE vehicle_model=$1 AND active=TRUE ORDER BY category,additional_price,option_name`,[model]);const grouped=rows.reduce((a,r)=>{(a[r.category]??=[]).push({id:r.id,name:r.option_name,price:Number(r.additional_price),imageUrl:r.image_url||null,metadata:r.metadata||{}});return a},{});res.json({data:{model,categories:grouped}})}catch(e){next(e)}});

app.post('/api/configurations',async(req,res,next)=>{const client=await getClient();try{const{model,vehicleId,optionIds=[],userId}=req.body||{};if(!model)return res.status(400).json({error:'Model is required'});if(!Array.isArray(optionIds))return res.status(400).json({error:'optionIds must be an array'});await client.query('BEGIN');let vehicle=null;if(vehicleId){const vr=await client.query(`SELECT id,model,price FROM vehicles WHERE id=$1 AND status<>'draft'`,[vehicleId]);vehicle=vr.rows[0]}if(!vehicle){const vr=await client.query(`SELECT id,model,price FROM vehicles WHERE model=$1 AND status='available' ORDER BY price LIMIT 1`,[model]);vehicle=vr.rows[0]}if(!vehicle){await client.query('ROLLBACK');return res.status(404).json({error:'No vehicle available for this model'})}const optRows=optionIds.length?await client.query(`SELECT id,option_name,category,additional_price FROM vehicle_options WHERE id=ANY($1::varchar[]) AND vehicle_model=$2 AND active=TRUE`,[optionIds,model]):{rows:[]};if(optRows.rows.length!==optionIds.length){await client.query('ROLLBACK');return res.status(400).json({error:'One or more selected options are invalid for this model'})}const optionsTotal=optRows.rows.reduce((s,r)=>s+Number(r.additional_price),0);const base=Number(vehicle.price);const total=base+optionsTotal;const financeMonthly=total>0?Number(((total-Math.min(250,total*0.1))*0.065/12/(1-Math.pow(1+0.065/12,-72))).toFixed(2)):0;const cid=id('CFG');const snapshot={model,vehicleId:vehicle.id,basePrice:base,options:optRows.rows.map(r=>({id:r.id,name:r.option_name,category:r.category,price:Number(r.additional_price)})),optionsTotal,totalPrice:total,financeMonthly};await client.query(`INSERT INTO configurations (id,user_id,vehicle_id,model,base_price,options_total,total_price,finance_monthly,deposit_amount,snapshot,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,250,$9,'draft')`,[cid,userId||null,vehicle.id,model,base,optionsTotal,total,financeMonthly,JSON.stringify(snapshot)]);for(const r of optRows.rows)await client.query(`INSERT INTO configuration_options (configuration_id,option_id,option_name,category,price) VALUES ($1,$2,$3,$4,$5)`,[cid,r.id,r.option_name,r.category,r.additional_price]);await client.query('COMMIT');res.status(201).json({data:{id:cid,...snapshot,depositAmount:250}})}catch(e){try{await client.query('ROLLBACK')}catch{}next(e)}finally{client.release()}});

app.post('/api/orders',async(req,res,next)=>{const client=await getClient();try{const{configurationId,name,email,phone='',notes='',delivery}=req.body||{};if(!configurationId||!name||!email)return res.status(400).json({error:'configurationId, name and email are required'});await client.query('BEGIN');const cfg=await client.query(`SELECT * FROM configurations WHERE id=$1 FOR UPDATE`,[configurationId]);if(!cfg.rows[0]){await client.query('ROLLBACK');return res.status(404).json({error:'Configuration not found'})}const c=cfg.rows[0];const oid=id('ORD'),tid=trackingId();let userId=c.user_id;const em=String(email).trim().toLowerCase();const ur=await client.query(`SELECT id FROM users WHERE email=$1`,[em]);if(ur.rows[0])userId=ur.rows[0].id;else{const u=await client.query(`INSERT INTO users (id,name,email,phone) VALUES ($1,$2,$3,$4) RETURNING id`,[id('USR'),String(name).trim(),em,phone]);userId=u.rows[0].id}const order=await client.query(`INSERT INTO orders (id,tracking_id,vehicle_id,user_id,configuration_id,customer_name,customer_email,customer_phone,total,deposit_amount,status,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'received',$11) RETURNING *`,[oid,tid,c.vehicle_id,userId,configurationId,String(name).trim(),em,phone,c.total_price,c.deposit_amount,notes]);await client.query(`UPDATE configurations SET user_id=$1,status='checkout',updated_at=NOW() WHERE id=$2`,[userId,configurationId]);if(delivery){await client.query(`INSERT INTO delivery_schedules (id,order_id,delivery_date,delivery_window,address_line1,city,state,postal_code) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,[id('DLV'),oid,delivery.date||null,delivery.window||null,delivery.address||null,delivery.city||null,delivery.state||null,delivery.zip||null])}await client.query(`INSERT INTO payments (id,order_id,amount,status) VALUES ($1,$2,$3,'pending')`,[id('PAY'),oid,c.deposit_amount]);await client.query(`INSERT INTO tracking_events (order_id,status,note) VALUES ($1,'Order Received',$2)`,[oid,'Order created; awaiting deposit payment.']);await client.query('COMMIT');res.status(201).json({data:orderFromRow(order.rows[0])})}catch(e){try{await client.query('ROLLBACK')}catch{}next(e)}finally{client.release()}});

app.post('/api/payments/create-checkout-session',async(req,res,next)=>{try{if(!stripe)return res.status(503).json({error:'Stripe is not configured on the server'});const{orderId}=req.body||{};const{rows}=await query(`SELECT o.*,v.model,c.snapshot FROM orders o LEFT JOIN vehicles v ON v.id=o.vehicle_id LEFT JOIN configurations c ON c.id=o.configuration_id WHERE o.id=$1`,[orderId]);const order=rows[0];if(!order)return res.status(404).json({error:'Order not found'});const session=await stripe.checkout.sessions.create({mode:'payment',line_items:[{price_data:{currency:'usd',product_data:{name:`TeslaMarketplace deposit — ${order.model||'Tesla vehicle'}`},unit_amount:Math.round(Number(order.deposit_amount)*100)},quantity:1}],metadata:{orderId:order.id,trackingId:order.tracking_id},customer_email:order.customer_email,success_url:`${process.env.FRONTEND_ORIGIN||'http://localhost:5173'}/?payment=success&tracking=${encodeURIComponent(order.tracking_id)}`,cancel_url:`${process.env.FRONTEND_ORIGIN||'http://localhost:5173'}/?payment=cancelled&tracking=${encodeURIComponent(order.tracking_id)}`});await query(`UPDATE payments SET provider_payment_id=$1,status='checkout_created',updated_at=NOW() WHERE order_id=$2 AND status='pending'`,[session.id,order.id]);res.json({data:{url:session.url,sessionId:session.id,trackingId:order.tracking_id}})}catch(e){next(e)}});
app.post('/api/payments/webhook',async(req,res)=>{if(!stripe)return res.status(503).send('Stripe not configured');let event;try{event=stripe.webhooks.constructEvent(req.body,req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET)}catch(e){return res.status(400).send(`Webhook Error: ${e.message}`)}try{if(event.type==='checkout.session.completed'){const s=event.data.object;const orderId=s.metadata?.orderId;if(orderId){await query(`UPDATE payments SET status='paid',provider_payment_id=$1,updated_at=NOW() WHERE order_id=$2`,[s.id,orderId]);await query(`UPDATE orders SET status='confirmed',updated_at=NOW() WHERE id=$1`,[orderId]);await query(`UPDATE configurations SET status='ordered',updated_at=NOW() WHERE id=(SELECT configuration_id FROM orders WHERE id=$1)`,[orderId]);await query(`INSERT INTO tracking_events (order_id,status,note) VALUES ($1,'Deposit Paid','Stripe confirmed the order deposit.')`,[orderId])}}if(event.type==='checkout.session.expired'){const s=event.data.object;const orderId=s.metadata?.orderId;if(orderId)await query(`UPDATE payments SET status='expired',updated_at=NOW() WHERE order_id=$1`,[orderId])}res.json({received:true})}catch(e){console.error(e);res.status(500).json({error:'Webhook processing failed'})}});

app.get('/api/orders/track/:trackingId',async(req,res,next)=>{try{const{rows}=await query(`SELECT o.*,v.model,v.year,v.image_url FROM orders o LEFT JOIN vehicles v ON v.id=o.vehicle_id WHERE o.tracking_id=$1`,[req.params.trackingId]);if(!rows[0])return res.status(404).json({error:'Tracking ID not found'});const events=await query(`SELECT status,note,created_at FROM tracking_events WHERE order_id=$1 ORDER BY created_at`,[rows[0].id]);const payment=await query(`SELECT status,amount,currency FROM payments WHERE order_id=$1 ORDER BY created_at DESC LIMIT 1`,[rows[0].id]);res.json({data:{...orderFromRow(rows[0]),vehicle:{model:rows[0].model,year:rows[0].year,imageUrl:rows[0].image_url},payment:payment.rows[0]||null,tracking:events.rows.map(e=>({status:e.status,note:e.note||'',createdAt:e.created_at}))}})}catch(e){next(e)}});
app.get('/api/orders',requireAuth,async(req,res,next)=>{try{const{rows}=await query(`SELECT * FROM orders WHERE user_id=$1 ORDER BY created_at DESC`,[req.user.userId]);res.json({data:rows.map(orderFromRow)})}catch(e){next(e)}});
app.get('/api/consignment-requests',async(req,res,next)=>{try{const{name,email,vehicleDescription}=req.body||{};if(!name||!email||!vehicleDescription)return res.status(400).json({error:'Name, email and vehicle description are required'});const r=await query(`INSERT INTO requests (id,type,name,email,message) VALUES ($1,'consignment',$2,$3,$4) RETURNING *`,[id('REQ'),name,email,vehicleDescription]);res.status(201).json({data:r.rows[0]})}catch(e){next(e)}});
app.get('/api/admin/orders',requireAuth,requireAdmin,async(_q,res,next)=>{try{const{rows}=await query(`SELECT * FROM orders ORDER BY created_at DESC`);res.json({data:rows.map(orderFromRow)})}catch(e){next(e)}});
app.use((req,res,next)=>{if(req.path.startsWith('/api')||req.path==='/health')return res.status(404).json({error:'API route not found'});next()});
app.use((err,_q,res,_n)=>{console.error(err);res.status(500).json({error:'Internal server error'})});
async function start(){if(!isDatabaseConfigured())return app.listen(PORT,'0.0.0.0',()=>console.log(`TeslaMarketplace API listening on port ${PORT} (database not configured)`));await initializeDatabase();const server=app.listen(PORT,'0.0.0.0',()=>console.log(`TeslaMarketplace API listening on port ${PORT}`));const shutdown=async()=>server.close(async()=>{await closeDatabase();process.exit(0)});process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown)}
if(require.main===module)start().catch(e=>{console.error('Failed to start TeslaMarketplace API:',e);process.exit(1)});
module.exports=app;
