const {query}=require('./db');
const {hashPassword}=require('./auth');
const ASSETS={'Model 3':'https://digitalassets.tesla.com/tesla-contents/image/upload/h_2560,w_4096,c_fit,f_auto,q_auto:best/Homepage-Model-3-Desktop-LHD','Model Y':'https://digitalassets.tesla.com/tesla-contents/image/upload/h_2400,w_2880,c_fit,f_auto,q_auto:best/Homepage-Model-Y-Global-Desktop','Model S':'https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/Homepage-Model-S-Desktop-LHD-6.22.jpg','Model X':'https://digitalassets.tesla.com/tesla-contents/image/upload/h_1800,w_2880,c_fit,f_auto,q_auto:best/Homepage-Model-X-Desktop-LHD'};
const models={'Model 3':{price:38990,range:363},'Model Y':{price:44990,range:321},'Model S':{price:79990,range:410},'Model X':{price:84990,range:335}};
const options={paint:[['Pearl White Multi-Coat',0],['Solid Black',1500],['Deep Blue Metallic',1500],['Ultra Red',2000]],wheels:[['18-inch Photon Wheels',0],['20-inch Induction Wheels',2000]],interior:[['All Black',0],['Black & White',2000],['Black & Tan',2500]],software:[['Autopilot',0],['Full Self-Driving (Supervised)',8500]]};
async function initializeDatabase(){
 await query(`CREATE TABLE IF NOT EXISTS users(id VARCHAR(64) PRIMARY KEY,name VARCHAR(160) NOT NULL,email VARCHAR(320) UNIQUE NOT NULL,phone VARCHAR(40),role VARCHAR(40) NOT NULL DEFAULT 'customer' CHECK(role IN ('customer','admin')),password_hash TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS vehicles(id VARCHAR(64) PRIMARY KEY,model VARCHAR(100) NOT NULL,year INTEGER NOT NULL,price NUMERIC(12,2) NOT NULL CHECK(price>=0),range_miles INTEGER NOT NULL DEFAULT 0,status VARCHAR(40) NOT NULL DEFAULT 'available',image_url TEXT,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS vehicle_options(id VARCHAR(64) PRIMARY KEY,vehicle_model VARCHAR(100) NOT NULL,category VARCHAR(40) NOT NULL,option_name VARCHAR(160) NOT NULL,additional_price NUMERIC(12,2) NOT NULL DEFAULT 0,image_url TEXT,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS configurations(id VARCHAR(64) PRIMARY KEY,user_id VARCHAR(64) REFERENCES users(id) ON DELETE SET NULL,vehicle_id VARCHAR(64) REFERENCES vehicles(id) ON DELETE SET NULL,model VARCHAR(100) NOT NULL,base_price NUMERIC(12,2) NOT NULL,options_total NUMERIC(12,2) NOT NULL DEFAULT 0,total_price NUMERIC(12,2) NOT NULL,finance_monthly NUMERIC(12,2),deposit_amount NUMERIC(12,2) NOT NULL DEFAULT 250,snapshot JSONB NOT NULL,status VARCHAR(40) NOT NULL DEFAULT 'draft',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS configuration_options(configuration_id VARCHAR(64) NOT NULL REFERENCES configurations(id) ON DELETE CASCADE,option_id VARCHAR(64) NOT NULL REFERENCES vehicle_options(id),option_name VARCHAR(160) NOT NULL,category VARCHAR(40) NOT NULL,price NUMERIC(12,2) NOT NULL DEFAULT 0,PRIMARY KEY(configuration_id,option_id));
 CREATE TABLE IF NOT EXISTS orders(id VARCHAR(64) PRIMARY KEY,tracking_id VARCHAR(80) UNIQUE NOT NULL,vehicle_id VARCHAR(64) REFERENCES vehicles(id),user_id VARCHAR(64) REFERENCES users(id),configuration_id VARCHAR(64) REFERENCES configurations(id) ON DELETE SET NULL,customer_name VARCHAR(160) NOT NULL,customer_email VARCHAR(320) NOT NULL,customer_phone VARCHAR(40),total NUMERIC(12,2) NOT NULL,deposit_amount NUMERIC(12,2) NOT NULL DEFAULT 250,status VARCHAR(40) NOT NULL DEFAULT 'received',notes TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS payments(id VARCHAR(64) PRIMARY KEY,order_id VARCHAR(64) NOT NULL REFERENCES orders(id) ON DELETE CASCADE,provider VARCHAR(40) NOT NULL DEFAULT 'stripe',provider_payment_id VARCHAR(255) UNIQUE,amount NUMERIC(12,2) NOT NULL,currency CHAR(3) NOT NULL DEFAULT 'USD',status VARCHAR(40) NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS delivery_schedules(id VARCHAR(64) PRIMARY KEY,order_id VARCHAR(64) UNIQUE NOT NULL REFERENCES orders(id) ON DELETE CASCADE,delivery_date DATE,delivery_window VARCHAR(80),address_line1 VARCHAR(240),city VARCHAR(120),state VARCHAR(80),postal_code VARCHAR(20),status VARCHAR(40) NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS tracking_events(id BIGSERIAL PRIMARY KEY,order_id VARCHAR(64) NOT NULL REFERENCES orders(id) ON DELETE CASCADE,status VARCHAR(80) NOT NULL,note TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 ALTER TABLE orders ADD COLUMN IF NOT EXISTS configuration_id VARCHAR(64) REFERENCES configurations(id) ON DELETE SET NULL;
 ALTER TABLE orders ADD COLUMN IF NOT EXISTS deposit_amount NUMERIC(12,2) NOT NULL DEFAULT 250;
 CREATE INDEX IF NOT EXISTS idx_vehicles_status ON vehicles(status);CREATE INDEX IF NOT EXISTS idx_vehicle_options_model_category ON vehicle_options(vehicle_model,category,active);CREATE INDEX IF NOT EXISTS idx_configurations_user ON configurations(user_id);CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id);CREATE INDEX IF NOT EXISTS idx_orders_tracking ON orders(tracking_id);CREATE INDEX IF NOT EXISTS idx_payments_order ON payments(order_id);CREATE INDEX IF NOT EXISTS idx_tracking_order ON tracking_events(order_id,created_at);`);
 for(const [model,data] of Object.entries(models))await query(`INSERT INTO vehicles(id,model,year,price,range_miles,status,image_url,metadata) VALUES($1,$2,2026,$3,$4,'available',$5,$6) ON CONFLICT(id) DO UPDATE SET price=EXCLUDED.price,range_miles=EXCLUDED.range_miles,image_url=EXCLUDED.image_url,metadata=EXCLUDED.metadata,updated_at=NOW()`,[`catalog-${model.toLowerCase().replace(/ /g,'-')}`,model,data.price,data.range,ASSETS[model],JSON.stringify({trim:'Long Range AWD',color:'Pearl White',body:model==='Model X'?'SUV':model==='Model Y'?'Midsize SUV':'Electric Sedan',zip:'08854'})]);
 for(const model of Object.keys(models))for(const [category,list] of Object.entries(options))for(const [name,price] of list){const oid=`${model.toLowerCase().replace(/ /g,'-')}-${category}-${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`;await query(`INSERT INTO vehicle_options(id,vehicle_model,category,option_name,additional_price,active) VALUES($1,$2,$3,$4,$5,TRUE) ON CONFLICT(id) DO UPDATE SET additional_price=EXCLUDED.additional_price,active=TRUE`,[oid,model,category,name,price]);}
 const adminEmail=String(process.env.ADMIN_EMAIL||'').trim().toLowerCase(),adminPassword=String(process.env.ADMIN_PASSWORD||'');if(adminEmail&&adminPassword){const exists=await query(`SELECT id,role FROM users WHERE email=$1`,[adminEmail]);if(!exists.rows[0])await query(`INSERT INTO users(id,name,email,role,password_hash) VALUES($1,$2,$3,'admin',$4)`,[`owner-${Date.now().toString(36)}`,process.env.ADMIN_NAME||'Marketplace Admin',adminEmail,await hashPassword(adminPassword)]);else if(exists.rows[0].role!=='admin')await query(`UPDATE users SET role='admin',updated_at=NOW() WHERE id=$1`,[exists.rows[0].id]);}
}
module.exports={initializeDatabase};
