import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import'./styles.css';import'./brand.css';
const API=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'');
const FALLBACK=['https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1600&q=90','https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1600&q=90','https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=1600&q=90','https://images.unsplash.com/photo-1597007066704-67bf2068d5b2?auto=format&fit=crop&w=1600&q=90'];
const meta=(v,k,f='')=>v?.metadata?.[k]??f;const image=(v,i=0)=>v?.imageUrl||v?.metadata?.imageUrl||FALLBACK[i%FALLBACK.length];
async function api(path,opt={}){const r=await fetch(`${API}${path}`,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const p=await r.json().catch(()=>({}));if(!r.ok)throw Error(p.error||`Request failed (${r.status})`);return p}
function App(){
 const[v,setV]=useState([]),[page,setPage]=useState('home'),[q,setQ]=useState(''),[model,setModel]=useState('all'),[status,setStatus]=useState('all'),[selected,setSelected]=useState(null),[gallery,setGallery]=useState(0),[notice,setNotice]=useState(''),[trackingId,setTrackingId]=useState(''),[tracking,setTracking]=useState(null),[orders,setOrders]=useState([]),[purchase,setPurchase]=useState({name:'',email:'',phone:'',notes:''}),[consign,setConsign]=useState({name:'',email:'',vehicleDescription:''}),[account,setAccount]=useState({name:'',email:'',password:''}),[user,setUser]=useState(null),[authMode,setAuthMode]=useState('login'),[busy,setBusy]=useState(false);
 const load=async()=>{try{const r=await api('/api/vehicles');setV(r.data||[]);setNotice('')}catch(e){setNotice(e.message)}};
 useEffect(()=>{load();const t=localStorage.getItem('tm_token');if(t)api('/api/me',{headers:{Authorization:`Bearer ${t}`}}).then(r=>setUser(r.data)).catch(()=>localStorage.removeItem('tm_token'))},[]);
 const models=useMemo(()=>[...new Set(v.map(x=>x.model))].sort(),[v]);const filtered=useMemo(()=>v.filter(x=>{const s=`${x.model} ${x.year} ${x.status} ${meta(x,'trim')} ${meta(x,'color')} ${meta(x,'body')}`.toLowerCase();return s.includes(q.toLowerCase())&&(model==='all'||x.model===model)&&(status==='all'||x.status===status)}),[v,q,model,status]);
 const nav=p=>{setPage(p);window.scrollTo({top:0,behavior:'smooth'})};const open=x=>{setSelected(x);setGallery(0)};
 async function auth(e){e.preventDefault();setBusy(true);try{const r=await api(authMode==='login'?'/api/auth/login':'/api/auth/register',{method:'POST',body:JSON.stringify(account)});localStorage.setItem('tm_token',r.data.token);setUser(r.data.user);setAccount({name:'',email:'',password:''});setNotice('Welcome to TeslaMarketplace.');nav('account')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 async function purchaseSubmit(e){e.preventDefault();if(!selected)return;setBusy(true);try{const r=await api('/api/purchase-requests',{method:'POST',body:JSON.stringify({vehicleId:selected.id,...purchase})});setTrackingId(r.data.trackingId);setTracking(r.data);setSelected(null);setPurchase({name:'',email:'',phone:'',notes:''});setNotice(`Request received — ${r.data.trackingId}`);nav('track');load()}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 async function track(e){e.preventDefault();setBusy(true);try{const r=await api(`/api/orders/track/${encodeURIComponent(trackingId.trim())}`);setTracking(r.data);setNotice('')}catch(e){setTracking(null);setNotice(e.message)}finally{setBusy(false)}}
 async function submitConsign(e){e.preventDefault();setBusy(true);try{await api('/api/consignment-requests',{method:'POST',body:JSON.stringify(consign)});setConsign({name:'',email:'',vehicleDescription:''});setNotice('Consignment request submitted for review.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 async function loadOrders(){const t=localStorage.getItem('tm_token');if(!t)return;try{const r=await api('/api/orders',{headers:{Authorization:`Bearer ${t}`}});setOrders(r.data||[])}catch(e){setNotice(e.message)}}
 function logout(){localStorage.removeItem('tm_token');setUser(null);setOrders([]);nav('home')}
 return <div className="app-shell"><Header page={page} nav={nav} user={user}/>{notice&&<div className="notice"><span>{notice}</span><button onClick={()=>setNotice('')}>×</button></div>}
 {page==='home'&&<Home vehicles={v} models={models} nav={nav} open={open}/>} {page==='inventory'&&<Inventory vehicles={filtered} models={models} q={q} setQ={setQ} model={model} setModel={setModel} status={status} setStatus={setStatus} open={open}/>} 
 {page==='charging'&&<Category title="Charging" kicker="CHARGING" text="Home and mobile charging equipment for electric driving." items={['Home charging equipment','Mobile charging','Adapters and cables','Charging accessories']}/>} 
 {page==='accessories'&&<Category title="Accessories" kicker="ACCESSORIES" text="Model-specific and universal equipment for daily driving, travel and protection." items={['Interior protection','Cargo and travel','Wheels and exterior','Technology and utility']}/>} 
 {page==='parts'&&<Category title="Parts & equipment" kicker="PARTS" text="Components, service equipment and replacement items." items={['Replacement components','Service equipment','Body and exterior parts','Interior components']}/>} 
 {page==='lifestyle'&&<Category title="Lifestyle" kicker="LIFESTYLE" text="Selected marketplace goods beyond the vehicle itself. Apparel is intentionally excluded." items={['Desk and home goods','Travel equipment','Vehicle-care goods','Limited marketplace items']}/>} 
 {page==='consign'&&<Consignment data={consign} setData={setConsign} submit={submitConsign} busy={busy}/>} {page==='track'&&<Tracking id={trackingId} setId={setTrackingId} data={tracking} submit={track} busy={busy}/>} 
 {page==='account'&&<Account user={user} orders={orders} loadOrders={loadOrders} id={trackingId} setId={setTrackingId} account={account} setAccount={setAccount} mode={authMode} setMode={setAuthMode} auth={auth} busy={busy} logout={logout} nav={nav}/>}<Footer nav={nav}/>
 {selected&&<Modal v={selected} gallery={gallery} setGallery={setGallery} close={()=>setSelected(null)} purchase={purchase} setPurchase={setPurchase} submit={purchaseSubmit} busy={busy}/>}</div>}
function Header({page,nav,user}){return <header className="site-header tm-nav"><div className="tm-shell tm-nav-inner"><button className="brand tm-brand" onClick={()=>nav('home')}><span className="brand-mark tm-brand-mark">TM</span><span>TeslaMarketplace</span></button><nav className="tm-nav-links"><button className={page==='home'?'active':''} onClick={()=>nav('home')}>Home</button><button className={page==='inventory'?'active':''} onClick={()=>nav('inventory')}>Vehicles</button><button className={page==='charging'?'active':''} onClick={()=>nav('charging')}>Charging</button><button className={page==='accessories'?'active':''} onClick={()=>nav('accessories')}>Accessories</button><button className={page==='parts'?'active':''} onClick={()=>nav('parts')}>Parts</button><button className={page==='consign'?'active':''} onClick={()=>nav('consign')}>Sell / Consign</button></nav><div className="nav-account"><button className="outline-button tm-btn" onClick={()=>nav('account')}>{user?'Account':'Sign in'}</button><button className="outline-button tm-btn tm-btn-dark" onClick={()=>nav('inventory')}>Browse</button></div></div></header>}
function Home({vehicles,models,nav,open}){return <><section className="hero tm-hero"><div className="tm-hero-inner home-layout"><div className="hero-copy"><span className="eyebrow tm-kicker">TESLAMARKETPLACE · 2026 COLLECTION</span><h1>Electric cars.<br/><em>Chosen differently.</em></h1><p>Shop current, pre-owned and previous-generation vehicles, then explore charging, accessories, parts and selected marketplace goods.</p><div className="hero-actions tm-actions"><button className="primary-button tm-btn tm-btn-dark" onClick={()=>nav('inventory')}>Explore inventory →</button><button className="text-button" onClick={()=>nav('track')}>Track an order</button></div><div className="hero-models"><span>{vehicles.length} listings</span><span>{models.length} models</span><span>Live marketplace</span></div></div><div className="hero-visual tm-media"><img src={image(vehicles[0])} alt="Featured electric vehicle"/><div className="hero-caption"><span>FEATURED INVENTORY</span><strong>{vehicles[0]?.model||'Electric vehicle'}</strong><small>{vehicles[0]?`${vehicles[0].year} · ${meta(vehicles[0],'trim','Available')}`:'Browse the marketplace'}</small></div></div></div></section><section className="tm-section tm-shell"><div className="section-top"><div><span className="eyebrow tm-kicker">MARKETPLACE</span><h2>Everything in one place.</h2></div></div><div className="feature-panels"><Feature title="Vehicles" text="Current and previous generations, trims and configurations." action={()=>nav('inventory')}/><Feature title="Charging" text="Home and mobile charging equipment." action={()=>nav('charging')}/><Feature title="Accessories" text="Model-specific and universal equipment." action={()=>nav('accessories')}/><Feature title="Parts" text="Components and service equipment." action={()=>nav('parts')}/><Feature title="Sell / Consign" text="Submit your vehicle for marketplace review." action={()=>nav('consign')}/></div></section><section className="tm-section tm-shell"><div className="section-top"><div><span className="eyebrow tm-kicker">VEHICLES</span><h2>Explore the lineup.</h2></div><button className="text-button" onClick={()=>nav('inventory')}>View all →</button></div><VehicleGrid vehicles={vehicles.slice(0,6)} open={open}/></section><section className="tm-section tm-shell split-banner"><div><span className="eyebrow tm-kicker">OWNERSHIP</span><h2>Find it. Request it. Track it.</h2><p>Browsing, purchase requests, accounts and tracking are connected.</p></div><button className="primary-button tm-btn tm-btn-dark" onClick={()=>nav('track')}>Track an order →</button></section></>}
function Feature({title,text,action}){return <button className="feature-panel" onClick={action}><span>{title}</span><strong>{text}</strong><small>Explore →</small></button>}
function Inventory({vehicles,models,q,setQ,model,setModel,status,setStatus,open}){return <section className="inventory-page tm-section tm-shell"><div className="page-heading"><span className="eyebrow tm-kicker">MARKETPLACE INVENTORY</span><h1>Choose your next vehicle.</h1><p>Search model, year, trim, color and availability.</p></div><div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search model, trim, color or year"/><select value={model} onChange={e=>setModel(e.target.value)}><option value="all">All models</option>{models.map(m=><option key={m} value={m}>{m}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All status</option><option value="available">Available</option><option value="reserved">Reserved</option></select></div>{vehicles.length?<VehicleGrid vehicles={vehicles} open={open}/>:<div className="empty">No vehicles match your search.</div>}</section>}
function VehicleGrid({vehicles,open}){return <div className="vehicle-grid tm-grid tm-grid-products">{vehicles.map((v,i)=><article className="vehicle-card tm-card" key={v.id} onClick={()=>open(v)} tabIndex="0" onKeyDown={e=>e.key==='Enter'&&open(v)}><div className="vehicle-image tm-media"><img src={image(v,i)} alt={`${v.year} ${v.model}`} loading="lazy"/><span className={`status-pill ${v.status}`}>{v.status}</span><span className="vehicle-color">{meta(v,'color','Color on request')}</span></div><div className="vehicle-info tm-content"><div className="vehicle-kicker"><span>{v.year}</span><span>{meta(v,'body')}</span></div><h3 className="tm-title">{v.model}</h3><p className="vehicle-trim tm-muted">{meta(v,'trim')} · {meta(v,'drive')}</p><div><strong className="tm-price">${Number(v.price).toLocaleString()}</strong><small>{v.range?` ${v.range} mi range`:''}</small></div></div></article>)}</div>}
function Modal({v,gallery,setGallery,close,purchase,setPurchase,submit,busy}){const imgs=[image(v,0),image(v,1),image(v,2),image(v,3)];return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal vehicle-modal"><button className="close" onClick={close}>×</button><div className="detail-gallery"><div className="gallery-main"><img key={gallery} src={imgs[gallery]} alt={`${v.model} view ${gallery+1}`}/><button className="gallery-arrow left" onClick={()=>setGallery((gallery+3)%4)}>‹</button><button className="gallery-arrow right" onClick={()=>setGallery((gallery+1)%4)}>›</button></div><div className="gallery-thumbs">{imgs.map((src,i)=><button type="button" className={gallery===i?'active':''} key={i} onClick={()=>setGallery(i)}><img src={src} alt={`${v.model} thumbnail ${i+1}`}/></button>)}</div></div><div className="modal-body"><span className="eyebrow tm-kicker">{v.year} · {meta(v,'body','ELECTRIC VEHICLE')}</span><h2>{v.model}</h2><div className="trim-line"><strong>{meta(v,'trim','Available configuration')}</strong><span>{meta(v,'color','Color on request')}</span></div><div className="vehicle-specs"><span><strong>${Number(v.price).toLocaleString()}</strong>Price</span><span><strong>{v.range??'—'}</strong>mi range</span><span><strong>{meta(v,'drive','—')}</strong>Drive</span></div><p>{meta(v,'description','Electric vehicle available through TeslaMarketplace.')}</p><div className="detail-tags"><span>{meta(v,'body')}</span><span>{meta(v,'color')}</span><span>{v.status}</span></div><h3>Submit purchase request</h3><form onSubmit={submit} className="purchase-form"><input required value={purchase.name} onChange={e=>setPurchase({...purchase,name:e.target.value})} placeholder="Full name"/><input required type="email" value={purchase.email} onChange={e=>setPurchase({...purchase,email:e.target.value})} placeholder="Email address"/><input value={purchase.phone} onChange={e=>setPurchase({...purchase,phone:e.target.value})} placeholder="Phone (optional)"/><textarea value={purchase.notes} onChange={e=>setPurchase({...purchase,notes:e.target.value})} placeholder="Notes (optional)" rows="3"/><button className="primary-button tm-btn tm-btn-dark" disabled={busy}>{busy?'Submitting…':'Submit purchase request'}</button></form></div></div></div>}
function Category({title,kicker,text,items}){return <section className="tm-section tm-shell category-page"><div className="page-heading"><span className="eyebrow tm-kicker">{kicker}</span><h1>{title}.</h1><p>{text}</p></div><div className="category-grid">{items.map((x,i)=><div className="category-card" key={x}><span>0{i+1}</span><h3>{x}</h3><p>Catalog area ready for inventory, pricing, specifications and availability.</p><button className="text-button">Explore →</button></div>)}</div></section>}
function Consignment({data,setData,submit,busy}){return <section className="tm-section tm-shell"><div className="page-heading"><span className="eyebrow tm-kicker">SELL / CONSIGN</span><h1>Put your vehicle on the marketplace.</h1><p>Submit vehicle details for review. The request is persisted in the backend.</p></div><form className="wide-form" onSubmit={submit}><input required placeholder="Full name" value={data.name} onChange={e=>setData({...data,name:e.target.value})}/><input required type="email" placeholder="Email address" value={data.email} onChange={e=>setData({...data,email:e.target.value})}/><textarea required minLength="10" rows="7" placeholder="Model, year, mileage, condition, location, options and other details" value={data.vehicleDescription} onChange={e=>setData({...data,vehicleDescription:e.target.value})}/><button className="primary-button tm-btn tm-btn-dark" disabled={busy}>{busy?'Submitting…':'Submit consignment request'}</button></form></section>}
function Tracking({id,setId,data,submit,busy}){return <section className="tracking-page tm-section tm-shell"><div className="page-heading"><span className="eyebrow tm-kicker">ORDER TRACKING</span><h1>Track your order.</h1><p>Enter the Tracking ID from your purchase request.</p></div><form className="tracking-form" onSubmit={submit}><input value={id} onChange={e=>setId(e.target.value)} placeholder="TMX-YYYYMMDD-XXXXXXXX" required/><button className="primary-button tm-btn tm-btn-dark" disabled={busy}>{busy?'Checking…':'Track order'}</button></form>{data&&<div className="tracking-card"><div className="tracking-head"><div><span className="eyebrow tm-kicker">TRACKING ID</span><h2>{data.trackingId}</h2></div><span className="order-status">{data.status}</span></div><div className="timeline">{(data.tracking||[]).map((e,i)=><div className="timeline-item" key={`${e.createdAt}-${i}`}><span className="timeline-dot"/><div><strong>{e.status}</strong><p>{e.note}</p><small>{new Date(e.createdAt).toLocaleString()}</small></div></div>)}</div></div>}</section>}
function Account({user,orders,loadOrders,id,setId,account,setAccount,mode,setMode,auth,busy,logout,nav}){useEffect(()=>{if(user)loadOrders()},[user]);if(!user)return <section className="tm-section tm-shell account-page"><div className="auth-layout"><div className="account-intro"><span className="eyebrow tm-kicker">TESLAMARKETPLACE ACCOUNT</span><h1>{mode==='login'?'Welcome back.':'Create your account.'}</h1><p>Sign in to view orders and keep marketplace activity in one place.</p></div><div className="tracking-card auth-card"><form className="purchase-form" onSubmit={auth}>{mode==='register'&&<input required minLength="2" placeholder="Full name" value={account.name} onChange={e=>setAccount({...account,name:e.target.value})}/>}<input required type="email" placeholder="Email address" value={account.email} onChange={e=>setAccount({...account,email:e.target.value})}/><input required minLength="8" type="password" placeholder="Password (8+ characters)" value={account.password} onChange={e=>setAccount({...account,password:e.target.value})}/><button className="primary-button tm-btn tm-btn-dark" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button></form><button className="text-button" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Create an account →':'Already registered? Sign in →'}</button></div></div></section>;
return <section className="tm-section tm-shell account-page"><div className="page-heading"><span className="eyebrow tm-kicker">ACCOUNT</span><h1>{user.name||user.email}.</h1><p>{user.email} · {user.role}</p></div><div className="account-grid"><div className="tracking-card"><span className="eyebrow tm-kicker">YOUR ORDERS</span>{orders.length?orders.map(o=><div className="order-row" key={o.id}><strong>{o.trackingId}</strong><span>{o.status}</span><button className="text-button" onClick={()=>{setId(o.trackingId);nav('track')}}>Track →</button></div>):<p className="tm-muted">No orders yet. Browse inventory to start a purchase request.</p>}<button className="primary-button tm-btn tm-btn-dark" onClick={()=>nav('inventory')}>Browse inventory</button></div><div className="tracking-card"><span className="eyebrow tm-kicker">ACCOUNT ACCESS</span><h3>Customer account</h3><p className="tm-muted">Customer accounts are separate from the protected owner/admin area.</p><button className="outline-button" onClick={logout}>Sign out</button></div></div></section>}
function Footer({nav}){return <footer className="tm-footer"><div className="tm-shell footer-grid"><div><strong>TeslaMarketplace</strong><p>Independent vehicle marketplace experience.</p></div><div><span>Shop</span><button onClick={()=>nav('inventory')}>Vehicles</button><button onClick={()=>nav('charging')}>Charging</button><button onClick={()=>nav('accessories')}>Accessories</button></div><div><span>Marketplace</span><button onClick={()=>nav('parts')}>Parts</button><button onClick={()=>nav('lifestyle')}>Lifestyle</button><button onClick={()=>nav('consign')}>Sell / Consign</button></div><div><span>Support</span><button onClick={()=>nav('track')}>Track order</button><button onClick={()=>nav('account')}>Account</button></div></div></footer>}
createRoot(document.getElementById('root')).render(<App/>);
